// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontValidationIssue } from "./FontValidationIssue";

/**
 * Validation details for a specific font.
 */
export type FontValidation = { isValid: boolean; issues: Array<FontValidationIssue> };
