// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontValidationSeverity } from "./FontValidationSeverity";

/**
 * A specific validation issue or warning.
 */
export type FontValidationIssue = { severity: FontValidationSeverity; message: string };
