// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A selected local/system font.
 */
export type FontSelection = {
  family: string;
  fullName: string;
  style: string;
  weight: number;
  path: string;
  faceIndex: number | null;
};
