// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { GameChroma } from "./GameChroma";

export type GameSkin = { skinNumber: number; skinName: string; chromas: Array<GameChroma> };
