// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSkin } from "./GameSkin";

export type GameChampion = { championId: string; championName: string; skins: Array<GameSkin> };
