// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectedChampion } from "./DetectedChampion";
import type { LeagueGameflowPhase } from "./LeagueGameflowPhase";
import type { LeagueSessionLifecycle } from "./LeagueSessionLifecycle";

export type LeagueSessionStateInner = {
  enabled: boolean;
  clientAvailable: boolean;
  phase: LeagueGameflowPhase;
  observedChampion: DetectedChampion | null;
  actualizedChampion: DetectedChampion | null;
  lifecycle: LeagueSessionLifecycle;
  lastError: string | null;
  lastUpdatedMs: bigint;
  currentSessionId: string | null;
};
