// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontSelection } from "./FontSelection";

/**
 * League font settings configured for this profile.
 */
export type LeagueFontSettings = { enabled: boolean; singleFont: FontSelection | null };
