// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A per-profile regular skin slot remap.
 */
export type SkinRemap = {
  championId: string;
  championName: string;
  targetSkinNumber: number;
  targetSkinName: string | null;
  targetChromaId: number | null;
  targetChromaName: string | null;
};
