// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontValidationIssue } from "./FontValidationIssue";

/**
 * Discovered system font.
 */
export type SystemFont = {
  family: string;
  fullName: string;
  style: string;
  weight: number;
  path: string;
  faceIndex: number | null;
  isValid: boolean;
  issues: Array<FontValidationIssue>;
};
